### ISSUE TITLE
Incorrect peer dependency error

### ISSUE THREAD

**Issue by Wartybliggens** [okonet/react-scroll-sync#15]
I'm getting errors when my project builds:
`warning "react-scroll-sync@0.4.0" has incorrect peer dependency "react@0.14.x || 15.x".
warning "react-scroll-sync@0.4.0" has incorrect peer dependency "react-dom@0.14.x || 15.x".`

Another problem is that our project is using React and react-dom version 16.

**Comment by okonet** [comment]
Please send a PR to fix this!

**Comment by Wartybliggens** [comment]
Done, thank you.

**Comment by Wartybliggens** [comment]
Thanks!

**Comment by okonet** [comment]
Thank you!
