### ISSUE TITLE
Deprecation of componentWillReceiveProps

### ISSUE THREAD

**Issue by Hugo-Contreras** [okonet/react-scroll-sync#21]
`componentWillReceiveProps` is deprecated since React 16.3.0, use UNSAFE_componentWillReceiveProps instead, see https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops

**Comment by okonet** [comment]
PR is welcome.

**Comment by tiagoqueiros** [comment]
Sorry for picking up this old issue, but I've been using this package recently and I've started receiving this warning aswell. I've opened a PR to update the deprecated lifecycle @okonet, can you please take a look?
