### ISSUE TITLE
Unit test component containing ScrollSyncPane without associated context

### ISSUE THREAD

**Issue by julietkb** [okonet/react-scroll-sync#33]
Pretty much the title. I have a component which does not have its own related context, and so unit testing is difficult since `this.context.registerPane` and `this.context.unregisterPane` aren't being mocked. Do I have to create a context for my component just to get the unit tests to work, or does `react-scroll-sync` have a way to handle this?

**Comment by okonet** [comment]
You’d have to mock it, yes.

**Comment by julietkb** [comment]
Can you provide an example? Thanks.

**Comment by okonet** [comment]
Sorry but no, you’d have to do the research yourself.
