### ISSUE TITLE
Incorrect peer dependency for react 17+

### ISSUE THREAD

**Issue by joaogardenberg** [okonet/react-scroll-sync#47]
Upon running `npm install` on my project:
```
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.5.4 || ^16.0.0" from react-scroll@1.8.1
npm ERR! node_modules/react-scroll
npm ERR!   react-scroll@"^1.8.1" from the root project
```

**Comment by okonet** [comment]
Yes peer does needs to be updated. Feel free to submit a PR to fix that!

**Comment by DILEEP-R-10** [comment]
npm ERR! Found: react@17.0.1

npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.5.4 || ^16.0.0" from react-scroll@1.8.1
npm ERR! node_modules/react-scroll
npm ERR!   react-scroll@"*" from the root project


couldn't find the solution can you kindly help me with this
