### ISSUE TITLE
Legacy context API and deprecated findDOMNode warnings

### ISSUE THREAD

**Issue by mmamedel** [okonet/react-scroll-sync#50]
Using in Strict Mode, React give this two warnings:
```
index.js:1 Warning: Legacy context API has been detected within a strict-mode tree.

The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.

Please update the following components: ScrollSync, ScrollSyncPane
```
and:
```
findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of ScrollSyncPane which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
```
More details of the issues are available in React documentation: [Link](https://reactjs.org/docs/strict-mode.html#warning-about-deprecated-finddomnode-usage)

**Comment by okonet** [comment]
You probably should not use this component with the latest React since it is using deprecated methods.

**Comment by mmamedel** [comment]
Do you plan to update it yourself? Or do you accept PRs?

**Comment by okonet** [comment]
I would love a PR! I don't plan to work on it myself. Would you like to do it? We can discuss the API first.

**Comment by mmamedel** [comment]
Seems like a similar work has already been done: https://github.com/AhmadMHawwash/scroll-sync-react#readme.
How far is it from your API? From a first look it seems pretty similar.

**Comment by okonet** [comment]
It even says it’s a fork of mine so I guess it has the same API. The fact that mine isn’t maintained isn’t true but if developers are more comfortable re-implementing things than working together then I’m fine with this too :)

Sincerely yours,
Andrey Okonetchnikov

@okonetchnikov • okonet.ru
