### ISSUE TITLE
Error: React.Children.only expected to receive a single React element child.

### ISSUE THREAD

**Issue by piotrgolawski** [okonet/react-scroll-sync#62]
I am trying to use your lib with react 17.0.14 on functional component.
Each time with error 
![image](https://user-images.githubusercontent.com/14168079/127124275-77a86b4a-2eed-41fc-9000-53cfcd5a2e92.png)
`
const [thead, theadRef] = useState();
<ScrollSync children={thead} />
`

or

![image](https://user-images.githubusercontent.com/14168079/127127462-1ac64ed8-e233-4521-b007-20a36dbf4d79.png)

I was also trying to use ScrollSyncPane directly in child components with enabled=false at start, but no luck.

I was also trying to pass children by attribute.

I need to sync scrolls from many components.
What I am doing wrong?

**Comment by okonet** [comment]
There are examples in the documentation how to do so. Did you read it?

**Comment by piotrgolawski** [comment]
Yes, they do not work, so I am asking. There are no components in examples, only html, so.... There is no usage of attachTo, what is object? ref? element?

**Comment by piotrgolawski** [comment]
<ScrollSync onSync={onSync} children={firstRef} /> -> Error: React.Children.only expected to receive a single React element child.

**Comment by piotrgolawski** [comment]
When I use ScrollSync on parent component and just put ScrollSyncPane in child 
![image](https://user-images.githubusercontent.com/14168079/127143073-05fca2e1-282e-4bfe-a7a8-5c6c571d797f.png)

**Comment by okonet** [comment]
I just checked and all examples work as expected. I guess you’re passing multiple children that’s what React is telling you. Please follow the examples. You can replace wrapper div with any other component. If you’re still struggling I can offer paid help / consulting. Let me know if you’re interested and I’ll send you over invoice details.

**Comment by piotrgolawski** [comment]
`You can replace wrapper div with any other component` how?
Why enabled={false} is catching all elements , it should wait for load (flag change).
What attachTo should receive? 
Why children is not allowing an array or even single ref element?
Why you use deprecated methods?

Lib is poor without good documentation and typings (YES!).

Work on bugfix and documentation before you are asking for payment, otherwise it is lame.

**Comment by okonet** [comment]
Okay this is kind of behavior I won’t tolerate in any of my repos. Please look for an alternative if you aren’t happy or send your PRs.

**Comment by piotrgolawski** [comment]
The fact you cannot answer basics without payment is below any level.
I wonder who tolerate that kind of work and attitude. Good luck

**Comment by piotrgolawski** [comment]
Nahhh, I will just look for an author with smaller ego. Good luck
